//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FancyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySmall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategorySmall()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int CategorySID { get; set; }
        public string CategorySName { get; set; }
        public int CategoryMID { get; set; }
    
        public virtual CategoryMiddle CategoryMiddle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
